### ISSUE TITLE
Question about date_submitted timezone

### ISSUE THREAD

**Issue by toshali** [gettyimages/gettyimages-api_java#18]
I'm sending an API call in the following way

```
client.searchimages()
          .withResponseFields(Arrays.asList("caption", "copyright","date_created","date_submitted","display_set","editorial_source","id","keywords","title"))
          .withPage((int) Math.floorDiv(offset, limit) + 1)
          .withPageSize(limit);
```

and the resulting JSON map contains dates for date_created and date_submitted in varying formats. I'm seeing dates come back in "yyyy-MM-dd'T'HH:mm:ss", "yyyy-MM-dd'T'HH:mm:ssZ", and "yyyy-MM-dd'T'HH:mm:ss.SSSZ". For the first format, is it safe to assume I should set the zone as UTC? Secondly, is there an enumeration in the docs somewhere of all the formats a downstream implementation is expected to handle? I'm depending on version `gettyimagesapi-sdk-3.1.2`.

Thank you!

**Comment by mapitman** [comment]
I'm surprised that you are getting a datetime back with no timezone information. Do you have an example of an image id that doesn't have the `Z` timezone identifier?

As for the format, any datetime string returned from the API should be compatible with [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by ChrisSimmons** [comment]
Closing this due to age.  If there are objections, let me know and I'll re-open.
