### ISSUE TITLE
Inconsistent default value for `auto_download` parameter

### ISSUE THREAD

**Issue by patrox** [gettyimages/gettyimages-api_java#19]
I've faced an issue while trying to download an image using the SDK, specifically the [DownloadImages#executeAsync](https://github.com/gettyimages/gettyimages-api_java/blob/main/src/main/java/com/gettyimages/api/Downloads/DownloadImages.java#L32) method, which uses the hardcoded `auto_download=false` property.

According to the swagger API spec the default value for `auto_download` is `true`:
[https://api.gettyimages.com/swagger/index.html#/Downloads/post_v3_downloads_images__id_](https://api.gettyimages.com/swagger/index.html#/Downloads/post_v3_downloads_images__id_)

Is there a possibility to change it, so either the default value is consistent with the docs, or even better - there is an option to set the `auto_download` field via dedicated method ?

I can submit a PR, if you don't have any objections.

**Comment by ChrisSimmons** [comment]
> I can submit a PR, if you don't have any objections.

No objections.  Please feel free!

**Comment by patrox** [comment]
> 



> > I can submit a PR, if you don't have any objections.
> 
> No objections. Please feel free!

Addressed in : https://github.com/gettyimages/gettyimages-api_java/pull/20
