### ISSUE TITLE
Token handling issue

### ISSUE THREAD

**Issue by ChrisSimmons** [gettyimages/gettyimages-api_java#4]
We received a report of a possible token handling issue.  In the following code, `response` is occasionally returned `null`.

``` java
final Images images = gettyApiClient.images()
    .withId(gettyId)
    .withResponseFields(METADATA_FIELDS);

final String response;
try {
    response = images.executeAsync();
} catch (final SdkException exception) {
    final String exceptionAsString = ExceptionUtils.getStackTrace(exception);
    throw new RuntimeException(String.format(gettyApiErrorMessage, exceptionAsString));
}
```

After analysis of the logs, it seems apparent that some calls were generating an `HTTP 401` from the API, indicating something wrong with the security token.  As token-handling should be done within the SDK, this may indicate something wrong with the handling logic.

**Comment by ssterli2** [comment]
This was fixed with version 2.1.1.
